### ISSUE TITLE
Disable Debug output

### ISSUE THREAD

**Issue by reijin90** [Crypto-toolbox/bitex#137]
Hi!

So far I like your work, it's a bit confusing to find a good example at first, but I guess I'll figure it out. 
Anyway, is there any way to disable the debug output from the console log? It's a bit annoying to see all the details. 

Greetings and keep it up! Helpful library :)

**Comment by thinknirmal** [comment]
It uses the standard logging library of Python, so you can configure it the way you want:

```
import logging

logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)
```

**Comment by nlsdfnbch** [comment]
@reijin90 , sorry for the late reply - the holidays keep me busy with the family :)
As for the solution to your problem, @thinknirmal already gave the correct answer!

**Comment by emestee** [comment]
Hi @nlsdfnbch,

Unfortunately this is a bug. In `interfaces` module, the following integrations call `logging.basicConfig()`: ccex, cryptopia, gemini, and yunbi. If prior to loading these integrations some code deconfigures logging output handlers, the call to `basicConfig()` will readd the default standard output again. 

Those calls should really be removed, libraries should not make assumptions about the state of the logging system.

**Comment by nlsdfnbch** [comment]
@emestee, you're correct. Removing those now
