### ISSUE TITLE
WSS tests

### ISSUE THREAD

**Issue by illera88** [Crypto-toolbox/bitex#145]
Hi,

do you have any example code I can use to see how to use the WSS version to get the tickers or order books? 

I have Bitstamp working but the code structure of the other exchanges seems to be completely different

Cheers

**Comment by nlsdfnbch** [comment]
Hey @illera88 ,
The websockets in `bitex` are deprecated and no longer maintained, so they may be out of date.
This is mainly due to the issue you point out - there were so many different API designs and protocols used, that it wasn't maintainable for me back when I first introduced them.
They ***may*** make a combat in future releases, but I am not actively planning to support websockets in `bitex` in the near future.

**Comment by jamesprinc3** [comment]
Hi @nlsdfnbch. Firstly, thank you for putting such a great project together. I want to make heavy use of the websocket wrappers in this repo for my final year project at university. I'm just wondering if you'd be willing to merge in any PRs that I may make over the next few months in this area of the codebase?

**Comment by emestee** [comment]
@nlsdfnbch would you accept related PRs? You should probably publish your policy and plans for 2.0, the deprecation warning is a bit scary :D

**Comment by nlsdfnbch** [comment]
@emestee , I probably should :D 
I'd take PRs, but Id keep them separate from the dev code base. For example, I could set up a feature branch for websocket implementations. Does this sound feasible to you two ?

**Comment by jamesprinc3** [comment]
@nlsdfnbch that's good to hear :) a different branch would be a reasonable solution if you want to keep it separate.

**Comment by nlsdfnbch** [comment]
I've added the branch `feature-websockets` knock yourselves out ;) I've been doing some migration and open-sourced my crypto toolbox entirely now - so have a look at project [`Thoth`](https://github.com/Crypto-toolbox/Thoth). It features a bunch of websocket connectors. It will be part of the Crypto Toolbox I'm working on, but currently only supports public channels.

I'll see about fleshing out the plans for `Crypto Toolbox` and its sub-projects and their goals, and publish them once they're ready.
