### ISSUE TITLE
Problem with API of Binance

### ISSUE THREAD

**Issue by Cloniko** [Crypto-toolbox/bitex#153]
Hello, 
im test binance and i receive a error.

My code:

print(Fore.LIGHTYELLOW_EX + '\nBINANCE -------------- TEST 1 ------------------------------------------------------------------\n')
Binancfg = Binance(config='%s/bitex/auth/binancerafa.ini' % ".")
Binanresp = Binancfg._get_supported_pairs()
logger.DEBUG('Binanresp ' + str(Binanresp))

Error:

BINANCE -------------- TEST 1 ------------------------------------------------------------------

2018-01-17 02:11:26,600 - DEBUG - Starting new HTTPS connection (1): api.binance.com
2018-01-17 02:11:28,394 - DEBUG - https://api.binance.com:443 "GET /v1/v1/exchangeInfo HTTP/1.1" 404 162
Traceback (most recent call last):
  File "testrafa.py", line 52, in <module>
    Binancfg = Binance(config='%s/bitex/auth/binancerafa.ini' % ".")
  File "C:\Bots\Test\bitex\interface\binance.py", line 24, in __init__
    super(Binance, self).__init__('Binance', BinanceREST(**api_kwargs))
  File "C:\Bots\Test\bitex\interface\rest.py", line 21, in __init__
    super(RESTInterface, self).__init__(name=name, rest_api=rest_api)
  File "C:\Bots\Test\bitex\interface\base.py", line 27, in __init__
    self._supported_pairs = self._get_supported_pairs()
  File "C:\Bots\Test\bitex\interface\binance.py", line 33, in _get_supported_pairs
    r = self.request('GET', 'v1/exchangeInfo').json()
  File "C:\Bots\Test\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Clk-w76416\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in load
s
    return _default_decoder.decode(s)
  File "C:\Users\Clk-w76416\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decod
e
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Clk-w76416\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_d
ecode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

BR

**Comment by Cloniko** [comment]
I see this

https://github.com/sammchardy/python-binance/tree/master/binance

https://github.com/sammchardy/python-binance/commit/6c967b7b0b9545a769d0dc086878a0dff4b37de6

Could it be the problem?

**Comment by nlsdfnbch** [comment]
The commit you referenced isn't a fix, but a workaround. I'll look into it today

**Comment by Cloniko** [comment]
I already know what the problem is with binance. The problem is the version of the api.

I change the value of the binance ini file. 
If i put 
[API]
version = api/v3
address = https://api.binance.com

and return self.request('GET', "v3/account", True).json() in interface\binance.py

Work perfectly but dont work def with v1 api.

**Comment by nlsdfnbch** [comment]
Oooh..well that's great. They use different API versions for different endpoints, according to their documentation. What a smart bunch of people. 
I'll fix this in the coming days.

**Comment by Cloniko** [comment]
only need change the value "api" in the auth/binance.ini

**Comment by nlsdfnbch** [comment]
No, that's incorrect. Changing that value means it would affect ALL endpoints - some endpoints, however, aren't on version 3 and require version 1.

**Comment by Cloniko** [comment]
Work fine

**Comment by nlsdfnbch** [comment]
The ticker endpoint, for example, does not:
https://api.binance.com/api/v3/ticker/24hr

**Comment by Cloniko** [comment]
wait a moment

**Comment by Cloniko** [comment]
Code:
print(Fore.LIGHTYELLOW_EX + '\nBINANCE -------------- TEST 1 ------------------------------------------------------------------\n')
Binancfg = Binance(config='%s/bitex/auth/binancerafa.ini' % ".")


Binanorders = Binancfg.order_book(Binanpair).json()
BinanBid = Binanorders['bids'][0][0]
BinanAsk = Binanorders['asks'][0][0]
BinanBidVol = Binanorders['bids'][0][1]
BinanAskVol = Binanorders['asks'][0][1]
print('Compra en Binance a ' + str(BinanAsk) + ' Cantidad: ' + str(BinanAskVol))
print('Venta en Binance a ' + str(BinanBid)+ ' Cantidad: ' + str(BinanBidVol))




BinanConBal = Binancfg.wallet()
for key in BinanConBal:
	Binanbal = {bal['asset']:bal['free']for bal in BinanConBal}
	BinanBase = Binanbal[base]
	BinanQuote = Binanbal[quote]
print('BinanBase ' + str(BinanBase))
print('BinanQuote ' + str(BinanQuote))

Resp:

XRPBTC

BINANCE -------------- TEST 1 ------------------------------------------------------------------

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.binance.com
2018-01-17 20:13:30,647 - DEBUG - Starting new HTTPS connection (1): api.binance.com
DEBUG:urllib3.connectionpool:https://api.binance.com:443 "GET /api/v1/exchangeInfo HTTP/1.1" 200 None
2018-01-17 20:13:31,992 - DEBUG - https://api.binance.com:443 "GET /api/v1/exchangeInfo HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.binance.com
2018-01-17 20:13:32,000 - DEBUG - Starting new HTTPS connection (1): api.binance.com
DEBUG:urllib3.connectionpool:https://api.binance.com:443 "GET /api/v1/depth?symbol=XRPBTC HTTP/1.1" 200 None
2018-01-17 20:13:33,299 - DEBUG - https://api.binance.com:443 "GET /api/v1/depth?symbol=XRPBTC HTTP/1.1" 200 N
one
Compra en Binance a 0.00010059 Cantidad: 4769.00000000
Venta en Binance a 0.00010058 Cantidad: 7986.00000000
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.binance.com
2018-01-17 20:13:33,305 - DEBUG - Starting new HTTPS connection (1): api.binance.com
DEBUG:urllib3.connectionpool:https://api.binance.com:443 "GET /api/v3/account?timestamp=1516216413302&signatur
e=ec9fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx86d59 HTTP/1.1" 200 None
2018-01-17 20:13:34,621 - DEBUG - https://api.binance.com:443 "GET /api/v3/account?timestamp=1516216413302&sig
nature=ec9f6160xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxaf86d59 HTTP/1.1" 200 None
BinanBase 0.02652165
BinanQuote 136.86100000

**Comment by nlsdfnbch** [comment]
Aaach right. I misread your config modification - yes, that's true; for binance the version value must be `api`, because I added version to the request string in the code.
