### ISSUE TITLE
Provide open_positions as a standardized method

### ISSUE THREAD

**Issue by metaperl** [Crypto-toolbox/bitex#160]
I am converting a script written for Bittrex to run on BitEx. 

Bittrex has an API method `cancelAllOrders` which basically gets all open transactions and then cancels each one.

There is a standardized method for cancelling an order [cancel_order](https://github.com/Crypto-toolbox/bitex/blob/master/bitex/interfaces/bittrex.py#L75) ... however I do not see a standardized method to list open positions.

This issue is somewhat related to [Promote closed_positions() to standardized method](https://github.com/Crypto-toolbox/bitex/issues/156)

**Comment by nlsdfnbch** [comment]
Hey @metaperl ,
This is already implemented on 2.0.0/dev and will be part of said release. 

Cheers, 
Nils
