### ISSUE TITLE
Symbolic access to compound response data?

### ISSUE THREAD

**Issue by metaperl** [Crypto-toolbox/bitex#164]
As it stands, it appears that the formatters return plain data that cannot be accessed symbolically. For instance, [the ticker method appears to return a tuple](https://github.com/Crypto-toolbox/bitex/blob/master/bitex/formatters/bittrex.py#L14).

This forces one to write code that is not symbolic - one must access what one wants by a "magic number" --- an index into a data structure instead of accessing it by an accessor.

In [issue 129](https://github.com/Crypto-toolbox/bitex/issues/129) there were some prototype response objects implemented and some appeared to return data in dictionaries or named tuples.

Is there a reason that the BitEx response object does not provide symbolic access to compound data  structures via something like a dictionary, named tuples or data classes?

**Comment by nlsdfnbch** [comment]
Responses are returned as namedtuples if their formatter was implemented correctly. Accessing their field names should therefore be possible.

What you've linked above is the master branch - this branch is outdated. All development and features are implemented on `dev`, which will replace the current release (`master`) in the future.
