### ISSUE TITLE
Switch from unittest to pytest

### ISSUE THREAD

**Issue by deepbrook** [Crypto-toolbox/bitex#187]

**Comment by firepol** [comment]
When you switch to pytest it would be really nice if you add a few commented examples and link to them from the contributing page. I'd put particular emphasis on how to fake data. Maybe some responses can be copied / pasted from other libraries (not necessarily in python, many are in nodejs, but we can take json responses from any place as long as they are valid).

**Comment by deepbrook** [comment]
Refactored the entire test suite to use pytest. In regards to the examples on how to fake data, we'll use `responses` to supply an API fixture which will take care of faking the exchange interface.
