### ISSUE TITLE
Why WSSAPI got removed in the dev branch?

### ISSUE THREAD

**Issue by firepol** [Crypto-toolbox/bitex#188]
Hi, I read in the [dev Changelog](https://github.com/Crypto-toolbox/bitex/blob/dev/Changelog.md)

"Websocket APIs have been removed."

Why? I actually wanted to test the websockets in the dev branch, and it's a pity that they got removed. Are they too hard to maintain? Is there another library that does this?

I believe bitex is a very interesting project: the python library that supports many exchanges, this is really awesome! Bitex could be used even to compare prices between exchanges... to have this feature in real time websockets should stay, not be removed...

Thoughts?

**Comment by deepbrook** [comment]
I've decided against WSS interface for bitex, as they're hard to unify as I did with the REST APIs. 
The code has since been moved to [thoth](https://github.com/Crypto-toolbox/Thoth), but I'm not yet confident how to properly test the porject and there is a lot to be done.
