### ISSUE TITLE
Exchange Market order on Bitfinex with REST API

### ISSUE THREAD

**Issue by torquemada163** [Crypto-toolbox/bitex#191]
Hello!

Do you can show me how make a Exchange Market order? And Exchange Limit, please!

Thanks!

**Comment by deepbrook** [comment]
Here's an example.
```
from bitex import Bitfinex
b = Bitfinex(key='api_key', secret='secret')
pair = 'btcusd'
price = '10000'
size = '1'
order_type = 'exchange market' # or 'exchange limit' for limit orders
b.ask(pair, price, size, type=order_type)  # b.bid to place a buy order
```
`kwargs` can be any parameter supported by the bitfinex API.

In order to keep things organized, please do NOT post comments asking for help in other issues - I'm aware of all of them, and will reply as soon as I find the time. Thanks!

**Comment by torquemada163** [comment]
Thank you very much!
