### ISSUE TITLE
Bitex no longer under development?

### ISSUE THREAD

**Issue by Jwely** [Crypto-toolbox/bitex#200]
Hi all, coming back to some crypto related programming and finding that this repo, which had some API's marked for deprecation, has in fact not changed at all for nearly a year.

Is this repo abandoned?

**Comment by deepbrook** [comment]
Hey @Jwely ,
Thanks for reaching out! 
It's currently not actively being maintained, unfortunately. I started working full time a year ago and had some pretty big personal changes which limit my available time.
I have been relying on contributors for all my projects over this time.
I will be on parental leave starting mid February and hope to have more time to get up to speed with my projects here on github.

Cheers,
Nils
