### ISSUE TITLE
Add Binance

### ISSUE THREAD

**Issue by nlsdfnbch** [Crypto-toolbox/bitex#79]
Url: 
https://www.binance.com/restapipub.html

Tasks:
- [ ] Tests
- [x] REST Wrapper
- [x] Pair Formatter
- [x] Interface

**Comment by Mukz95** [comment]
Hi, Interested in picking up this ticket. new to open source :)

**Comment by nlsdfnbch** [comment]
Hey @Mukz95 !
Great to hear you want to contribute! I'd suggest to first get acquainted with the code base of `BitEx`. Take a look at how we do things around here. If you feel like you have a grasp of what's going on (or if you don't, do not hesitate to ask!) and fork the repository. 
Start committing your code (be sure to read `[bitex/CONTRIBUTING.md](https://github.com/nlsdfnbch/bitex/blob/master/CONTRIBUTING.md)` for requirements) and once you're done simply submit your pull request.

I'll check it out as soon as I can and leave feedback if it needs improvements / fixes, or simply merge it if everything's fine. 

Also note that you do not have to submit a PR containing ALL the above points, but must always supply tests for your new code (so you may submit a new `PairFormatter` with tests, without having to supply REST wrappers or interface functions, etc).

**Comment by Mukz95** [comment]
Yes just trying to understand the codebase, I was wondering 
if [ https://github.com/Mukz95/bitex/blob/master/tests/formatters.py](url) tests pass? I was looking into the code didn't see how they were supposed to pass, unless i have missed something or are they meant to fail for now and pass when implementation takes place?

**Comment by nlsdfnbch** [comment]
Actually, I'm not sure - I've added them at some point and somewhat abandoned the tests on `master` right after - but these changes are all meant for the 2.0 release, hence you should develop from `master` (there everything *should* work - there's also more tests). 

Sorry it's all a little confusing. Trying to clean it up for excellent people like you willing to contribute!

**Comment by HughMacdonald** [comment]
@Mukz95 are you planning on continuing work on this one? If not, I would be interested in picking up the rest of this

**Comment by HughMacdonald** [comment]
Actually... I'm afraid that I already started on this one.

I've got the REST part working - I need to work through the interface class now.

@nlsdfnbch would you like me to PR the REST part, or wait until I can do both the REST and the Interface?

**Comment by nlsdfnbch** [comment]
@HughMacdonald , either way is fine!

**Comment by HughMacdonald** [comment]
Done. Initial REST api implementation in #120

**Comment by HughMacdonald** [comment]
How do you like to deal with additional required parameters to methods?

For example, both order_status and cancel_order on Binance are going to require the pair that the order is on. Am I okay to add this to the method definition, or do you want to ensure that all method definitions are identical between exchanges, and insist on the extra parameters being passed in through kwargs?

Thanks

**Comment by HughMacdonald** [comment]
Actually, now all in #122. I took it in a direction that I felt okay with - happy to change it if you'd prefer.

Binance has the basic methods implemented, but I want to go through and put additional methods in place.

**Comment by nlsdfnbch** [comment]
Merged! Thanks @HughMacdonald!

**Comment by metaperl** [comment]
If this has been merged, should it be listed under [supported exchanges](https://github.com/Crypto-toolbox/bitex#supported-exchanges)?

**Comment by nlsdfnbch** [comment]
Yes it should be - I usually update it before a release, but if you want, feel free to add it to the table

**Comment by karlandoh** [comment]
Has this been merged yet? We are waiting.

**Comment by deepbrook** [comment]
It has been merged already. It may not be on pypi yet - feel free to pip install via the `dev` branch to get the latest version for now
